// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cache/cache_iface.go

// Package cache is a generated GoMock package.
package cache

import (
	models "microservice/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheIface is a mock of CacheIface interface.
type MockCacheIface struct {
	ctrl     *gomock.Controller
	recorder *MockCacheIfaceMockRecorder
}

// MockCacheIfaceMockRecorder is the mock recorder for MockCacheIface.
type MockCacheIfaceMockRecorder struct {
	mock *MockCacheIface
}

// NewMockCacheIface creates a new mock instance.
func NewMockCacheIface(ctrl *gomock.Controller) *MockCacheIface {
	mock := &MockCacheIface{ctrl: ctrl}
	mock.recorder = &MockCacheIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheIface) EXPECT() *MockCacheIfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCacheIface) Get(key string) (*models.Order, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheIfaceMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheIface)(nil).Get), key)
}

// Set mocks base method.
func (m *MockCacheIface) Set(key string, order *models.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, order)
}

// Set indicates an expected call of Set.
func (mr *MockCacheIfaceMockRecorder) Set(key, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheIface)(nil).Set), key, order)
}

// SetValidated mocks base method.
func (m *MockCacheIface) SetValidated(key string, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValidated", key, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValidated indicates an expected call of SetValidated.
func (mr *MockCacheIfaceMockRecorder) SetValidated(key, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValidated", reflect.TypeOf((*MockCacheIface)(nil).SetValidated), key, order)
}
